### ISSUE TITLE
Shortcode delimiter

### ISSUE THREAD

**Issue by bep** [wildhaber/gohugo-amp#15]
I notice that most of your shortcode example use `{{%` (will render inner content as markdown) and not what I believe is a better fit: `{{<` 

Also, Hugo supports "commented out" Shortcodes, so instead of:

```
{\{% partial "test/lipsum" %}\}
```

You wan write:

```
{{%/* partial "test/lipsum" */%}}
```

**Comment by wildhaber** [comment]
hey @bep

thanks for your explainations 👍 

I had to read the shortcode documentation again because I missinterpretated the difference between `{{%` and `{{<`. I thought the `%` you should use when you want to use the shortcode in a markdown file instead of when you need to have markdown rendered in your shortcode. Small but significant difference :-) thanks.

As well I was looking so long for a "commented out" solution.

I'll make the changes in the next update.

**Comment by bep** [comment]
>As well I was looking so long for a "commented out" solution.

I don't think it's documented, I just needed it to document the shortcodes. A PR with a line in the shortcode section is welcomed.

And also note that when I say "inner content" above, I mean the content between the opening and closing shortcode. You may not have much of that, and then the delimiter does not make much practical difference.

**Comment by wildhaber** [comment]
Documentation is updated now.

I'll have a look later on for a documentation update PR in the Hugo-Repo.
