### ISSUE TITLE
"above the fold" Issue 

### ISSUE THREAD

**Issue by Schokolader** [wildhaber/gohugo-amp#34]
Google page speed shows the issue to reduce the "above the fold" html elements: 

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgohugo-amp.gohugohq.com%2Fkitchen-sink%2F&tab=desktop

**Comment by wildhaber** [comment]
Since this theme is a base starter template for amp pages and this issue is obvious for a very long scrolling page with a lot of elements including full css in the head-section (as required from amp) this is an expected notice from page speed insights.

You can absolutely avoid this in your custom integration usage for your website.
